version: "3.8"

services:
    back:
        build: .
        ports:
            - 8080:80
        working_dir: /var/www
        volumes:
            - ./:/var/www
        environment:
            MYSQL_HOST: host-mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_DB: tutoants
    front:
        image: node:12.21
        working_dir: /app
        command: sh -c "npm install && npm install -g @angular/cli@7.2.4 && ng build --output-path=./../build/angular --watch"
        volumes:
            - ../ants-wiki-front:/app
            - ./public/js:/build
    host-mysql:
        image: mysql:5.7
        volumes:
            - volume-mysql:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: tutoants
            
volumes:
    volume-mysql:
    volume-build:


